#!/usr/bin/env bash
# shell script that displays best school 10 times 
# on the 9th iteration displays best school then hi on a new line

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
