#!/usr/bin/env bash
# Displays best school for each iteration except the 4th and 8th
# Display Bad luck for 4th iteration
# Display Good luck for 8th iteration

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
