#!/usr/bin/env bash
# Shell script that loops from 1 to 20 in addtion to:
# 4 then bad luck from China for the 4th iteration
# 9 then bad luck from Japan for the 9th iteration
# 17 then bad luck from Italy for the 17th iteration

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done
